Traceback (most recent call last):
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/client.py", line 608, in async_setup_kernel
    yield
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/corrado/opt/anaconda3/envs/pymc_511/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
psych::omega(d[, 1:6])
------------------

Error in omegah(m = m, nfactors = nfactors, fm = fm, key = key, flip = flip, : I am sorry, you need to have the  GPArotation package installed
Traceback:

1. psych::omega(d[, 1:6])
2. omegah(m = m, nfactors = nfactors, fm = fm, key = key, flip = flip, 
 .     digits = digits, title = title, sl = sl, labels = labels, 
 .     plot = plot, n.obs = n.obs, rotate = rotate, Phi = Phi, option = option, 
 .     covar = covar, ...)
3. stop("I am sorry, you need to have the  GPArotation package installed")
ERROR: Error in omegah(m = m, nfactors = nfactors, fm = fm, key = key, flip = flip, : I am sorry, you need to have the  GPArotation package installed


